name: Development CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: run dev routine
      run: make dev
